/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package notepad;

import java.util.Arrays;
import java.util.Comparator;
import javax.swing.JTextField;

/**
 *
 * @author Shreyas
 */
public class Dictionary extends javax.swing.JFrame {

    /**
     * Creates new form Dictionary
     */
    
    String str[];
    int index=0;
    int size=10000;
    String sugg[];
    int sugNum=10;
    int btnIndex=0;
    int suggestions=0;
    Editor mainAct;
    
    public Dictionary(Editor mainAct) {
        initComponents();
        str=new String[size];
        sugg=new String[sugNum];
        this.mainAct=mainAct;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.95F);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addWord(String w) {
        index=(index+1)%size;
        str[index]=w;
//        Arrays.sort(str,new Comparator<String>(){
//            @Override
//            public int compare(String a,String b) {
//                return (a.toLowerCase()).compareTo(b.toLowerCase());
//            }
//        });
    }
    
    public void delete() {
        str=new String[size];
    }
    
    public void getSuggestion(String w) {
        suggestions=0;
        for (int i=0;i<size;i++){
            if (str[i]!=null&&str[i].startsWith(w)) {
                sugg[suggestions++]=str[i];
            }
            if (suggestions>=sugNum) {
                break;
            }
        }
    }
    
    public void show(int x,int y) {
        JTextField suggest[] = new JTextField[suggestions];
        for (int i=0;i<suggestions;i++) {
            suggest[i]=new JTextField();
            suggest[i].setEditable(false);
            suggest[i].setText(sugg[i]);
            //suggest[i].setLocation(i*100,i*100);
            btnIndex=i;
            getContentPane().add(suggest[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30*i, 239, -1));
            suggest[i].addMouseListener(new java.awt.event.MouseAdapter() {
                int id=btnIndex;
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    giveString(suggest[id].getText());
                }
            });
        }
        
        pack();
        this.setLocation(x,y);
        this.setVisible(true);
        
    }
    
    public void giveString(String s) {
        System.out.println(s);
        mainAct.followSuggestion(s);
        this.setVisible(false);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
